apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thischart.fullname" . }}
  labels:
{{ include "thischart.labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "thischart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "thischart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: opulence-logoverride-webhook-account
      containers:
      - name: {{ .Chart.Name }}
        image: {{ if .Values.imageName }}{{ .Values.imageName }}{{ else }}"{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"{{ end }}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: TLS_CERT_FILE
          value: /var/cert/tls.crt
        - name: TLS_KEY_FILE
          value: /var/cert/tls.key
        ports:
        - containerPort: 80
        volumeMounts:
        - name: cert
          mountPath: /var/cert
          readOnly: true
      volumes:
      - name: cert
        secret:
          secretName: opulence-logoverride-webhook-cert
