name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.0.0
      with:
        version: 3.1.100
     
    - name: dotnet build
      run: dotnet build opulence.sln -c Release
      
    - name: dotnet test
      run: dotnet test opulence.sln -c Release --no-build

    - name: dotnet pack
      run: |
        mkdir ./artifacts
        dotnet pack opulence.sln -c Release --no-build -o ./artifacts

    - name: setup nuget
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      uses: NuGet/setup-nuget@v1.0.2
      with:
        nuget-version: latest

    - name: add package repository
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: nuget source Add -Config nuget.config -Name github -Source https://nuget.pkg.github.com/rynowak/index.json -UserName rynowak -Password ${{ secrets.GITHUB_TOKEN }} -StorePasswordInClearText

    - name: push packages
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
          for f in ./artifacts/*.nupkg
          do
            curl --silent --show-error --fail -vX PUT -u "rynowak:${{ secrets.GITHUB_TOKEN }}" -F package=@$f https://nuget.pkg.github.com/rynowak/
            if [ $? -eq 0 ]
            then
              echo "successfully pushed $f"
            else
              echo "failed to push $f" >&2
              exit 1
            fi
          done
